.body-regular {
  font-family: var(--font-secondary);
  font-weight: var(--font-secondary-400);
  font-size: 16px;
}

.body-medium {
  font-family: var(--font-secondary);
  font-weight: var(--font-secondary-500);
  font-size: 14px;
}

.caption {
  font-family: var(--font-secondary);
  font-weight: var(--font-secondary-400);
  font-size: 12px;
}

.label-uppercase {
  font-family: var(--font-secondary);
  font-weight: var(--font-secondary-700);
  font-size: 11px;
  letter-spacing: 1.5px;
}